<?php

namespace Duf\CoreBundle\Entity\Repository;

/**
 * DufCoreSeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DufCoreSeoRepository extends \Doctrine\ORM\EntityRepository
{
}
