<?php

namespace Duf\CoreBundle\Entity\Repository;

/**
* DufCoreNotificationTypeRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class DufCoreNotificationTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByDistinctDoctrineEvents()
	{
		$qb   = $this->_em->createQueryBuilder()
						  ->select('DISTINCT(nt.eventAction)')
						  ->from($this->_entityName, 'nt')
						  ->where('nt.enabled = 1')
						  ->andWhere('nt.listenerType = :doctrine_type')
						  ->setParameter('doctrine_type', 'doctrine');

		$events 	= array();
		$results 	= $qb->getQuery()->getResult();

		foreach ($results as $result) {
			if (isset($result[1]))
				$events[] = $result[1];
		}

		return $events;
	}

	public function findByDistinctDoctrineEntities()
	{
		$qb   = $this->_em->createQueryBuilder()
						  ->select('DISTINCT(nt.eventClass)')
						  ->from($this->_entityName, 'nt')
						  ->where('nt.enabled = 1')
						  ->andWhere('nt.listenerType = :doctrine_type')
						  ->setParameter('doctrine_type', 'doctrine');

		$entities 	= array();
		$results 	= $qb->getQuery()->getResult();

		foreach ($results as $result) {
			if (isset($result[1]))
				$entities[] = $result[1];
		}

		return $entities;
	}

	public function findByDistinctTargetClasses()
	{
		$qb   = $this->_em->createQueryBuilder()
						  ->select('DISTINCT(nt.targetClass)')
						  ->from($this->_entityName, 'nt')
						  ->where('nt.enabled = 1');

		$entities 	= array();
		$results 	= $qb->getQuery()->getResult();

		foreach ($results as $result) {
			if (isset($result[1]))
				$entities[] = $result[1];
		}

		return $entities;
	}
}
